x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: 50

services:
  server:
    restart: always
    logging: *default-logging
    depends_on:
      - vector-serve
    image: ghcr.io/chuckhend/vectorize-server:latest
    ports:
      - 8080:8080
    environment:
      EMBEDDING_SVC_URL: ${EMBEDDING_SVC_URL:-http://vector-serve:3000/v1}
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@host.docker.internal:5432/postgres}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RUST_LOG: ${RUST_LOG:-info}
    command: vectorize-server
  vector-serve:
    restart: always
    logging: *default-logging
    image: ghcr.io/chuckhend/vector-serve:latest
    ports:
      - 3000:3000
    environment:
      HF_API_KEY: ${HF_API_KEY}
