events {}

http {
  upstream vector_serve {
    server vector-serve:3000;
    server vector-serve-2:3000;
  }

  server {
    listen 3000;
    location / {
      proxy_pass http://vector_serve;
      proxy_read_timeout 120s;
      proxy_send_timeout 120s;
    }
  }
}
